"""CMAReportAgent — generates Comparative Market Analysis reports.

Pulls property data + comparable sales from existing scrapers, generates
a narrative analysis via Claude, and produces a styled HTML report.
"""
import logging
import uuid

from sqlalchemy import select

from listingjet.database import AsyncSessionLocal
from listingjet.models.brand_kit import BrandKit
from listingjet.models.cma_report import CMAReport
from listingjet.models.listing import Listing
from listingjet.models.property_data import PropertyData
from listingjet.providers import get_llm_provider
from listingjet.services.comparables import ComparablesService
from listingjet.services.pii_filter import sanitize_for_prompt
from listingjet.services.storage import StorageService

from .base import AgentContext, BaseAgent

logger = logging.getLogger(__name__)

_CMA_PROMPT = """\
You are a real estate market analyst. Generate a brief Comparative Market Analysis narrative
for the subject property based on the comparable sales data below.

Subject Property:
{subject_details}

Comparable Sales:
{comparables_text}

Write 2-3 paragraphs covering:
1. How the subject compares to recent sales (price per sqft, condition, features)
2. Suggested pricing range based on the comparables
3. Market conditions and expected time on market

Be factual and professional. Return plain text, no JSON or markdown."""

_CMA_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
body {{ font-family: 'Helvetica Neue', Arial, sans-serif; margin: 40px; color: #1e293b; }}
h1 {{ color: {primary_color}; margin-bottom: 5px; }}
h2 {{ color: #334155; border-bottom: 2px solid {primary_color}; padding-bottom: 8px; }}
.meta {{ color: #64748b; font-size: 14px; margin-bottom: 30px; }}
table {{ border-collapse: collapse; width: 100%; margin: 20px 0; }}
th {{ background: {primary_color}; color: white; padding: 10px 12px; text-align: left; font-size: 13px; }}
td {{ border-bottom: 1px solid #e2e8f0; padding: 10px 12px; font-size: 13px; }}
tr:hover td {{ background: #f8fafc; }}
.analysis {{ line-height: 1.7; color: #475569; }}
.footer {{ margin-top: 40px; padding-top: 20px; border-top: 1px solid #e2e8f0; font-size: 12px; color: #94a3b8; }}
</style>
</head>
<body>
<h1>Comparative Market Analysis</h1>
<p class="meta">{address} &mdash; Prepared by {agent_name}</p>

<h2>Subject Property</h2>
<table>
<tr><th>Beds</th><th>Baths</th><th>Sqft</th><th>Year Built</th><th>Property Type</th></tr>
<tr><td>{beds}</td><td>{baths}</td><td>{sqft}</td><td>{year_built}</td><td>{property_type}</td></tr>
</table>

<h2>Comparable Sales</h2>
<table>
<tr><th>Address</th><th>Beds</th><th>Baths</th><th>Sqft</th><th>Sale Price</th><th>Price/Sqft</th></tr>
{comp_rows}
</table>

<h2>Analysis</h2>
<div class="analysis">{analysis}</div>

<div class="footer">
Generated by ListingJet CMA &mdash; {agent_name}, {brokerage_name}
</div>
</body>
</html>
"""


class CMAReportAgent(BaseAgent):
    agent_name = "cma_report"
    requires_ai_consent = True

    def __init__(
        self,
        llm_provider=None,
        storage_service=None,
        session_factory=None,
        comparables_service: ComparablesService | None = None,
    ):
        self._llm = llm_provider or get_llm_provider(agent=self.agent_name)
        self._storage = storage_service or StorageService()
        self._session_factory = session_factory or AsyncSessionLocal
        self._comparables = comparables_service or ComparablesService()

    async def execute(self, context: AgentContext) -> dict:
        async with self.session_scope(context) as (session, listing_id, tenant_id):
            listing = await session.get(Listing, listing_id)
            if not listing:
                raise ValueError(f"Listing {listing_id} not found")

            # Load property data
            prop = (await session.execute(
                select(PropertyData).where(PropertyData.listing_id == listing_id)
            )).scalar_one_or_none()

            address = listing.address or {}
            meta = listing.metadata_ or {}

            # Build subject details
            subject = {
                "address": f"{address.get('street', '')}, {address.get('city', '')}, {address.get('state', '')}",
                "beds": prop.beds if prop else meta.get("beds"),
                "baths": prop.baths if prop else meta.get("baths"),
                "sqft": prop.sqft if prop else meta.get("sqft"),
                "year_built": prop.year_built if prop else meta.get("year_built"),
                "property_type": prop.property_type if prop else meta.get("property_type", "single_family"),
                "price": meta.get("price"),
            }

            # Fetch comparables — Repliers if enabled + configured, synthetic fallback otherwise.
            comparables = await self._comparables.fetch(subject)

            # Generate analysis narrative via LLM
            comps_text = "\n".join(
                f"- {c['address']}: {c['beds']}bd/{c['baths']}ba, {c['sqft']}sqft, "
                f"sold ${c['price']:,} (${c['price_per_sqft']}/sqft)"
                for c in comparables
            )

            safe_subject = sanitize_for_prompt(subject)
            analysis = await self._llm.complete(
                prompt=_CMA_PROMPT.format(
                    subject_details=str(safe_subject),
                    comparables_text=comps_text,
                ),
                context=safe_subject,
                temperature=0.3,
            )

            # Load brand kit for styling
            brand_kit = (await session.execute(
                select(BrandKit).where(BrandKit.tenant_id == tenant_id).limit(1)
            )).scalar_one_or_none()

            primary_color = brand_kit.primary_color if brand_kit else "#2563EB"
            agent_name = brand_kit.agent_name if brand_kit else "Agent"
            brokerage_name = brand_kit.brokerage_name if brand_kit else ""

            # Render HTML
            comp_rows = "\n".join(
                f"<tr><td>{c['address']}</td><td>{c['beds']}</td><td>{c['baths']}</td>"
                f"<td>{c['sqft']:,}</td><td>${c['price']:,}</td><td>${c['price_per_sqft']}</td></tr>"
                for c in comparables
            )

            html = _CMA_HTML_TEMPLATE.format(
                primary_color=primary_color,
                address=subject["address"],
                agent_name=agent_name,
                brokerage_name=brokerage_name,
                beds=subject["beds"] or "—",
                baths=subject["baths"] or "—",
                sqft=f"{subject['sqft']:,}" if subject["sqft"] else "—",
                year_built=subject["year_built"] or "—",
                property_type=(subject["property_type"] or "—").replace("_", " ").title(),
                comp_rows=comp_rows,
                analysis=analysis.replace("\n", "<br>"),
            )

            # Upload HTML to S3
            s3_key = f"listings/{listing_id}/cma-report-{uuid.uuid4().hex[:8]}.html"
            self._storage.upload(s3_key, html.encode("utf-8"), content_type="text/html")

            # Save to database
            report = CMAReport(
                tenant_id=tenant_id,
                listing_id=listing_id,
                subject_address=address,
                comparables=comparables,
                analysis_summary=analysis[:5000],
                pdf_s3_key=s3_key,
                comparables_count=len(comparables),
            )
            session.add(report)

            await self.emit(session, context, "cma_report.completed", {
                "listing_id": str(listing_id),
                "comparables_count": len(comparables),
                "s3_key": s3_key,
            })

        return {"comparables_count": len(comparables), "s3_key": s3_key}
