"""Generate `.env.example` from `listingjet.config.Settings`.

Usage:
    python scripts/gen_env_example.py           # (re)write .env.example
    python scripts/gen_env_example.py --check   # exit 1 if .env.example is stale

Iterates `Settings.model_fields` in declaration order and emits one line per
field: `KEY=<default>` for ordinary fields (booleans lowercased, list-like
defaults comma-joined, `None` rendered as empty). Any field whose name
contains "key", "secret", "password", "token", "dsn", or ends with "_url" is
treated as sensitive: it is always emitted blank (`KEY=`) with a trailing
`# secret` comment, regardless of what real default it may have.

Fields are grouped under comment headers derived from the section comments
in `listingjet/config/__init__.py` (a `# Section Name` line that immediately
follows a blank line introduces a new section; every field defined after it,
until the next such header, belongs to that section) — so the generated file
tracks `Settings`' own organization without needing a second source of truth.
"""

from __future__ import annotations

import argparse
import inspect
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "src"))

from listingjet.config import Settings  # noqa: E402

ENV_EXAMPLE_PATH = REPO_ROOT / ".env.example"

SECRET_SUBSTRINGS = ("key", "secret", "password", "token", "dsn")

HEADER = """# ─────────────────────────────────────────────
# ListingJet — Environment Configuration
# Generated by scripts/gen_env_example.py from listingjet.config.Settings —
# do not hand-edit; run `python scripts/gen_env_example.py` to regenerate
# (or `just env-example`). `just env-check` / `--check` fails CI if this
# file has drifted from Settings.
#
# Copy to .env and fill in your values. Local dev typically also sets:
#   USE_MOCK_PROVIDERS=true     (skip real Anthropic/OpenAI calls)
#   FFMPEG_BIN=/path/to/ffmpeg  (if ffmpeg isn't on PATH)
# ─────────────────────────────────────────────"""


def is_secret(name: str) -> bool:
    return any(s in name for s in SECRET_SUBSTRINGS) or name.endswith("_url")


def format_default(value: object) -> str:
    if value is None:
        return ""
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (list, tuple, set)):
        return ",".join(str(v) for v in value)
    return str(value)


def section_map() -> dict[str, str | None]:
    """Map each field name to the section comment that introduces its block."""
    source = inspect.getsource(Settings)
    sections: dict[str, str | None] = {}
    current: str | None = None
    prev_blank = True
    field_re = re.compile(r"^    (\w+)\s*:")
    for line in source.splitlines():
        stripped = line.strip()
        if not stripped:
            prev_blank = True
            continue
        if stripped.startswith("#") and prev_blank:
            current = stripped.lstrip("#").strip()
            prev_blank = False
            continue
        match = field_re.match(line)
        if match:
            name = match.group(1)
            sections.setdefault(name, current)
        prev_blank = False
    return sections


def generate_lines() -> list[str]:
    sections = section_map()
    lines = [HEADER]
    last_section: object = object()  # sentinel, never equal to a real section
    for name, field in Settings.model_fields.items():
        section = sections.get(name)
        if section != last_section:
            lines.append("")
            label = section or "Other"
            lines.append(f"# ── {label} " + "─" * max(1, 44 - len(label)))
            last_section = section
        key = name.upper()
        if is_secret(name):
            lines.append(f"{key}=  # secret")
        else:
            default = None if field.is_required() else field.default
            lines.append(f"{key}={format_default(default)}")
    return lines


def generate_content() -> str:
    return "\n".join(generate_lines()) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if .env.example would change instead of writing it",
    )
    args = parser.parse_args()

    content = generate_content()

    if args.check:
        existing = (
            ENV_EXAMPLE_PATH.read_text(encoding="utf-8") if ENV_EXAMPLE_PATH.exists() else None
        )
        if existing != content:
            print(
                f"{ENV_EXAMPLE_PATH} is out of date with listingjet.config.Settings; "
                "run `python scripts/gen_env_example.py` to regenerate.",
                file=sys.stderr,
            )
            return 1
        print(f"{ENV_EXAMPLE_PATH} is up to date.")
        return 0

    ENV_EXAMPLE_PATH.write_text(content, encoding="utf-8")
    print(f"Wrote {ENV_EXAMPLE_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
